// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lexblmrlnfyznjfqvhqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxleGJsbXJsbmZ5em5qZnF2aHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NjQyOTEsImV4cCI6MjA1ODM0MDI5MX0.BRfTPry3_oDXl0FH4pbyYplUhgneWOifrhB2IQReRkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);